controllers:
    resource:
        path: ../src/Controller/
        namespace: Orion\Controller
    type: attribute

#api:
#    path: /api
#    controller: Orion\Controller\ApiController::getRoot
#    methods: ['GET']

#api_users:
#    path: /api/users
#    controller: Orion\Controller\ApiController::getUsers
#    methods: ['GET']

admin:
    path: /admin
    controller: Orion\Controller\AdminController::getAdmin
    methods: ['GET']
